// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: docs.proto

package main

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Warnings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Warnings []*Warnings_Warning `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
}

func (x *Warnings) Reset() {
	*x = Warnings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warnings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warnings) ProtoMessage() {}

func (x *Warnings) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warnings.ProtoReflect.Descriptor instead.
func (*Warnings) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{0}
}

func (x *Warnings) GetWarnings() []*Warnings_Warning {
	if x != nil {
		return x.Warnings
	}
	return nil
}

type Warnings_Warning struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          []string `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
	Header        string   `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Description   string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Autofix       bool     `protobuf:"varint,4,opt,name=autofix,proto3" json:"autofix,omitempty"`
	BazelFlag     string   `protobuf:"bytes,5,opt,name=bazel_flag,json=bazelFlag,proto3" json:"bazel_flag,omitempty"`
	BazelFlagLink string   `protobuf:"bytes,6,opt,name=bazel_flag_link,json=bazelFlagLink,proto3" json:"bazel_flag_link,omitempty"`
}

func (x *Warnings_Warning) Reset() {
	*x = Warnings_Warning{}
	if protoimpl.UnsafeEnabled {
		mi := &file_docs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Warnings_Warning) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Warnings_Warning) ProtoMessage() {}

func (x *Warnings_Warning) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Warnings_Warning.ProtoReflect.Descriptor instead.
func (*Warnings_Warning) Descriptor() ([]byte, []int) {
	return file_docs_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Warnings_Warning) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Warnings_Warning) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *Warnings_Warning) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Warnings_Warning) GetAutofix() bool {
	if x != nil {
		return x.Autofix
	}
	return false
}

func (x *Warnings_Warning) GetBazelFlag() string {
	if x != nil {
		return x.BazelFlag
	}
	return ""
}

func (x *Warnings_Warning) GetBazelFlagLink() string {
	if x != nil {
		return x.BazelFlagLink
	}
	return ""
}

var File_docs_proto protoreflect.FileDescriptor

var file_docs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x64, 0x6f,
	0x63, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x08, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x32, 0x0a, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x73, 0x2e, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e, 0x69,
	0x6e, 0x67, 0x73, 0x1a, 0xb8, 0x01, 0x0a, 0x07, 0x57, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x75, 0x74, 0x6f, 0x66, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x61, 0x75, 0x74, 0x6f, 0x66, 0x69, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x7a, 0x65, 0x6c,
	0x5f, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x7a,
	0x65, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x26, 0x0a, 0x0f, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x5f,
	0x66, 0x6c, 0x61, 0x67, 0x5f, 0x6c, 0x69, 0x6e, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x62, 0x61, 0x7a, 0x65, 0x6c, 0x46, 0x6c, 0x61, 0x67, 0x4c, 0x69, 0x6e, 0x6b, 0x42, 0x34,
	0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x61, 0x7a,
	0x65, 0x6c, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x2f, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x74, 0x6f, 0x6f,
	0x6c, 0x73, 0x2f, 0x76, 0x34, 0x2f, 0x77, 0x61, 0x72, 0x6e, 0x2f, 0x64, 0x6f, 0x63, 0x73, 0x3b,
	0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_docs_proto_rawDescOnce sync.Once
	file_docs_proto_rawDescData = file_docs_proto_rawDesc
)

func file_docs_proto_rawDescGZIP() []byte {
	file_docs_proto_rawDescOnce.Do(func() {
		file_docs_proto_rawDescData = protoimpl.X.CompressGZIP(file_docs_proto_rawDescData)
	})
	return file_docs_proto_rawDescData
}

var file_docs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_docs_proto_goTypes = []interface{}{
	(*Warnings)(nil),         // 0: docs.Warnings
	(*Warnings_Warning)(nil), // 1: docs.Warnings.Warning
}
var file_docs_proto_depIdxs = []int32{
	1, // 0: docs.Warnings.warnings:type_name -> docs.Warnings.Warning
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_docs_proto_init() }
func file_docs_proto_init() {
	if File_docs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_docs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warnings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_docs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Warnings_Warning); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_docs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_docs_proto_goTypes,
		DependencyIndexes: file_docs_proto_depIdxs,
		MessageInfos:      file_docs_proto_msgTypes,
	}.Build()
	File_docs_proto = out.File
	file_docs_proto_rawDesc = nil
	file_docs_proto_goTypes = nil
	file_docs_proto_depIdxs = nil
}
