// Code generated by protoc-gen-go. DO NOT EDIT.
// source: deps_proto/deps.proto

package deps_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dependency_Kind int32

const (
	Dependency_EXPLICIT   Dependency_Kind = 0
	Dependency_IMPLICIT   Dependency_Kind = 1
	Dependency_UNUSED     Dependency_Kind = 2
	Dependency_INCOMPLETE Dependency_Kind = 3
)

var Dependency_Kind_name = map[int32]string{
	0: "EXPLICIT",
	1: "IMPLICIT",
	2: "UNUSED",
	3: "INCOMPLETE",
}
var Dependency_Kind_value = map[string]int32{
	"EXPLICIT":   0,
	"IMPLICIT":   1,
	"UNUSED":     2,
	"INCOMPLETE": 3,
}

func (x Dependency_Kind) Enum() *Dependency_Kind {
	p := new(Dependency_Kind)
	*p = x
	return p
}
func (x Dependency_Kind) String() string {
	return proto.EnumName(Dependency_Kind_name, int32(x))
}
func (x *Dependency_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Dependency_Kind_value, data, "Dependency_Kind")
	if err != nil {
		return err
	}
	*x = Dependency_Kind(value)
	return nil
}
func (Dependency_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_deps_dad00a5b66e605b7, []int{1, 0}
}

type SourceLocation struct {
	Path                 *string  `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Line                 *int32   `protobuf:"varint,2,opt,name=line" json:"line,omitempty"`
	Column               *int32   `protobuf:"varint,3,opt,name=column" json:"column,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SourceLocation) Reset()         { *m = SourceLocation{} }
func (m *SourceLocation) String() string { return proto.CompactTextString(m) }
func (*SourceLocation) ProtoMessage()    {}
func (*SourceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_deps_dad00a5b66e605b7, []int{0}
}
func (m *SourceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SourceLocation.Unmarshal(m, b)
}
func (m *SourceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SourceLocation.Marshal(b, m, deterministic)
}
func (dst *SourceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SourceLocation.Merge(dst, src)
}
func (m *SourceLocation) XXX_Size() int {
	return xxx_messageInfo_SourceLocation.Size(m)
}
func (m *SourceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_SourceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_SourceLocation proto.InternalMessageInfo

func (m *SourceLocation) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *SourceLocation) GetLine() int32 {
	if m != nil && m.Line != nil {
		return *m.Line
	}
	return 0
}

func (m *SourceLocation) GetColumn() int32 {
	if m != nil && m.Column != nil {
		return *m.Column
	}
	return 0
}

type Dependency struct {
	Path                 *string           `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Kind                 *Dependency_Kind  `protobuf:"varint,2,req,name=kind,enum=blaze_deps.Dependency_Kind" json:"kind,omitempty"`
	Location             []*SourceLocation `protobuf:"bytes,3,rep,name=location" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dependency) Reset()         { *m = Dependency{} }
func (m *Dependency) String() string { return proto.CompactTextString(m) }
func (*Dependency) ProtoMessage()    {}
func (*Dependency) Descriptor() ([]byte, []int) {
	return fileDescriptor_deps_dad00a5b66e605b7, []int{1}
}
func (m *Dependency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependency.Unmarshal(m, b)
}
func (m *Dependency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependency.Marshal(b, m, deterministic)
}
func (dst *Dependency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependency.Merge(dst, src)
}
func (m *Dependency) XXX_Size() int {
	return xxx_messageInfo_Dependency.Size(m)
}
func (m *Dependency) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependency.DiscardUnknown(m)
}

var xxx_messageInfo_Dependency proto.InternalMessageInfo

func (m *Dependency) GetPath() string {
	if m != nil && m.Path != nil {
		return *m.Path
	}
	return ""
}

func (m *Dependency) GetKind() Dependency_Kind {
	if m != nil && m.Kind != nil {
		return *m.Kind
	}
	return Dependency_EXPLICIT
}

func (m *Dependency) GetLocation() []*SourceLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

type Dependencies struct {
	Dependency                       []*Dependency `protobuf:"bytes,1,rep,name=dependency" json:"dependency,omitempty"`
	RuleLabel                        *string       `protobuf:"bytes,2,opt,name=rule_label,json=ruleLabel" json:"rule_label,omitempty"`
	Success                          *bool         `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
	ContainedPackage                 []string      `protobuf:"bytes,4,rep,name=contained_package,json=containedPackage" json:"contained_package,omitempty"`
	RequiresReducedClasspathFallback *bool         `protobuf:"varint,5,opt,name=requires_reduced_classpath_fallback,json=requiresReducedClasspathFallback" json:"requires_reduced_classpath_fallback,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}      `json:"-"`
	XXX_unrecognized                 []byte        `json:"-"`
	XXX_sizecache                    int32         `json:"-"`
}

func (m *Dependencies) Reset()         { *m = Dependencies{} }
func (m *Dependencies) String() string { return proto.CompactTextString(m) }
func (*Dependencies) ProtoMessage()    {}
func (*Dependencies) Descriptor() ([]byte, []int) {
	return fileDescriptor_deps_dad00a5b66e605b7, []int{2}
}
func (m *Dependencies) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dependencies.Unmarshal(m, b)
}
func (m *Dependencies) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dependencies.Marshal(b, m, deterministic)
}
func (dst *Dependencies) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dependencies.Merge(dst, src)
}
func (m *Dependencies) XXX_Size() int {
	return xxx_messageInfo_Dependencies.Size(m)
}
func (m *Dependencies) XXX_DiscardUnknown() {
	xxx_messageInfo_Dependencies.DiscardUnknown(m)
}

var xxx_messageInfo_Dependencies proto.InternalMessageInfo

func (m *Dependencies) GetDependency() []*Dependency {
	if m != nil {
		return m.Dependency
	}
	return nil
}

func (m *Dependencies) GetRuleLabel() string {
	if m != nil && m.RuleLabel != nil {
		return *m.RuleLabel
	}
	return ""
}

func (m *Dependencies) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Dependencies) GetContainedPackage() []string {
	if m != nil {
		return m.ContainedPackage
	}
	return nil
}

func (m *Dependencies) GetRequiresReducedClasspathFallback() bool {
	if m != nil && m.RequiresReducedClasspathFallback != nil {
		return *m.RequiresReducedClasspathFallback
	}
	return false
}

func init() {
	proto.RegisterType((*SourceLocation)(nil), "blaze_deps.SourceLocation")
	proto.RegisterType((*Dependency)(nil), "blaze_deps.Dependency")
	proto.RegisterType((*Dependencies)(nil), "blaze_deps.Dependencies")
	proto.RegisterEnum("blaze_deps.Dependency_Kind", Dependency_Kind_name, Dependency_Kind_value)
}

func init() { proto.RegisterFile("deps_proto/deps.proto", fileDescriptor_deps_dad00a5b66e605b7) }

var fileDescriptor_deps_dad00a5b66e605b7 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x5f, 0x6b, 0xdb, 0x30,
	0x14, 0xc5, 0x67, 0x3b, 0xed, 0x92, 0xbb, 0x12, 0x32, 0xc1, 0x8a, 0xd8, 0x18, 0x98, 0xec, 0xc5,
	0x6c, 0xa0, 0x42, 0x1f, 0xfa, 0xb8, 0x87, 0xa5, 0x19, 0x84, 0x25, 0x5d, 0x50, 0x5b, 0xd8, 0x9b,
	0x91, 0xa5, 0xbb, 0x4c, 0x44, 0x95, 0x3c, 0xcb, 0xee, 0xd8, 0xbe, 0xe1, 0x3e, 0xd3, 0x5e, 0x86,
	0x94, 0x3f, 0x6d, 0x21, 0x6f, 0xe7, 0x1c, 0xff, 0xee, 0xf5, 0xf1, 0xc5, 0xf0, 0x4a, 0x61, 0xed,
	0xcb, 0xba, 0x71, 0xad, 0x3b, 0x0b, 0x92, 0x45, 0x49, 0xa0, 0x32, 0xe2, 0x0f, 0x96, 0x21, 0x19,
	0x2f, 0x61, 0x78, 0xed, 0xba, 0x46, 0xe2, 0xdc, 0x49, 0xd1, 0x6a, 0x67, 0x09, 0x81, 0x5e, 0x2d,
	0xda, 0x1f, 0x34, 0xc9, 0xd3, 0x62, 0xc0, 0xa3, 0x0e, 0x99, 0xd1, 0x16, 0x69, 0x9a, 0x27, 0xc5,
	0x11, 0x8f, 0x9a, 0x9c, 0xc2, 0xb1, 0x74, 0xa6, 0xbb, 0xb3, 0x34, 0x8b, 0xe9, 0xd6, 0x8d, 0xff,
	0x26, 0x00, 0x97, 0x58, 0xa3, 0x55, 0x68, 0xe5, 0xef, 0x83, 0xeb, 0xce, 0xa0, 0xb7, 0xd6, 0x56,
	0xd1, 0x34, 0x4f, 0x8b, 0xe1, 0xf9, 0x1b, 0xf6, 0xd0, 0x87, 0x3d, 0x4c, 0xb2, 0x2f, 0xda, 0x2a,
	0x1e, 0x41, 0x72, 0x01, 0x7d, 0xb3, 0xed, 0x47, 0xb3, 0x3c, 0x2b, 0x5e, 0x9c, 0xbf, 0x7e, 0x3c,
	0xf4, 0xf4, 0x0b, 0xf8, 0x9e, 0x1d, 0x7f, 0x84, 0x5e, 0xd8, 0x42, 0x4e, 0xa0, 0x3f, 0xfd, 0xb6,
	0x9c, 0xcf, 0x26, 0xb3, 0x9b, 0xd1, 0xb3, 0xe0, 0x66, 0x8b, 0xad, 0x4b, 0x08, 0xc0, 0xf1, 0xed,
	0xd5, 0xed, 0xf5, 0xf4, 0x72, 0x94, 0x92, 0x21, 0xc0, 0xec, 0x6a, 0xf2, 0x75, 0xb1, 0x9c, 0x4f,
	0x6f, 0xa6, 0xa3, 0x6c, 0xfc, 0x2f, 0x81, 0x93, 0x7d, 0x23, 0x8d, 0x9e, 0x5c, 0x00, 0xa8, 0x7d,
	0x43, 0x9a, 0xc4, 0x2a, 0xa7, 0x87, 0xfb, 0xf3, 0x47, 0x24, 0x79, 0x0b, 0xd0, 0x74, 0x06, 0x4b,
	0x23, 0x2a, 0x34, 0xf1, 0x8c, 0x03, 0x3e, 0x08, 0xc9, 0x3c, 0x04, 0x84, 0xc2, 0x73, 0xdf, 0x49,
	0x89, 0xde, 0xc7, 0x63, 0xf6, 0xf9, 0xce, 0x92, 0x0f, 0xf0, 0x52, 0x3a, 0xdb, 0x0a, 0x6d, 0x51,
	0x95, 0xb5, 0x90, 0x6b, 0xb1, 0x42, 0xda, 0xcb, 0xb3, 0x62, 0xc0, 0x47, 0xfb, 0x07, 0xcb, 0x4d,
	0x4e, 0x16, 0xf0, 0xae, 0xc1, 0x9f, 0x9d, 0x6e, 0xd0, 0x97, 0x0d, 0xaa, 0x4e, 0xa2, 0x2a, 0xa5,
	0x11, 0xde, 0x87, 0xab, 0x97, 0xdf, 0x85, 0x31, 0x95, 0x90, 0x6b, 0x7a, 0x14, 0x5f, 0x91, 0xef,
	0x50, 0xbe, 0x21, 0x27, 0x3b, 0xf0, 0xf3, 0x96, 0xfb, 0xf4, 0x1e, 0x0a, 0xe9, 0xee, 0xd8, 0xca,
	0xb9, 0x95, 0x41, 0xa6, 0xf0, 0xbe, 0x75, 0xce, 0x78, 0x56, 0x75, 0xda, 0x28, 0x66, 0x74, 0xc5,
	0xee, 0x35, 0xfe, 0xda, 0xfc, 0x53, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x44, 0xb2, 0x9b,
	0x6b, 0x02, 0x00, 0x00,
}
